backend:
  name: git-gateway
  branch: main # Altere para a branch principal do seu repositório

media_folder: "assets/img" # Pasta onde as imagens serão armazenadas
public_folder: "/assets/img"

media2_folder: "assets/img/icon" # Pasta onde as imagens serão armazenadas
public2_folder: "/assets/img/icon"

media3_folder: "assets/img/shape" # Pasta onde as imagens serão armazenadas
public3_folder: "/assets/img/shape"


collections:

  - name: "pages" # Nome da coleção
    label: "Páginas"
    files:
      - name: "index"
        label: "Página Inicial"
        file: "index.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "html" } # Use o widget html para editar HTML diretamente

      - name: "about-us"
        label: "Sobre Nós"
        file: "about-us.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "html" } # Use o widget html para editar HTML diretamente

      - name: "contact-us"
        label: "Contato"
        file: "contact-us.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "html" } # Use o widget html para editar HTML diretamente

      - name: "404"
        label: "Página 404"
        file: "404.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "html" } # Use o widget html para editar HTML diretamente

      - name: "services"
        label: "Serviços"
        file: "services.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "html" } # Use o widget html para editar HTML diretamente

      - name: "portfolio"
        label: "Portfólio"
        file: "portfolio.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "html" } # Use o widget html para editar HTML diretamente

      - name: "team"
        label: "Equipe"
        file: "team.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "html" } # Use o widget html para editar HTML diretamente

      # Adicione outras páginas conforme necessário

  - name: "assets"
    label: "Imagens e Arquivos"
    folder: "assets/img"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Arquivo", name: "file", widget: "file" }

  - name: "config"
    label: "Configurações do Site"
    files:
      - name: "settings"
        label: "Configurações"
        file: "data/settings.yml"
        fields:
          - { label: "Título do Site", name: "site_title", widget: "string" }
          - { label: "Descrição do Site", name: "site_description", widget: "text" }
          - { label: "E-mail de Contato", name: "contact_email", widget: "string" }
          - { label: "Links Sociais", name: "social_links", widget: "object", fields: [
              { label: "Twitter", name: "twitter", widget: "string" },
              { label: "Facebook", name: "facebook", widget: "string" },
              { label: "Instagram", name: "instagram", widget: "string" }
            ]}
