backend:
  name: git-gateway
  branch: main # Altere para a branch principal do seu repositório

media_folder: "assets/img" # Pasta onde as imagens serão armazenadas
public_folder: "/assets/img"

collections:
  - name: "pages" # Nome da coleção
    label: "Páginas"
    files:
      - name: "index"
        label: "Página Inicial"
        file: "index.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "about-us"
        label: "Sobre Nós"
        file: "about-us.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "contact-us"
        label: "Contato"
        file: "contact-us.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "404"
        label: "Página 404"
        file: "404.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "services"
        label: "Serviços"
        file: "services.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "portfolio"
        label: "Portfólio"
        file: "portfolio.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "team"
        label: "Equipe"
        file: "team.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      # Adicione outras páginas conforme necessário
      - name: "blog-standard"
        label: "Blog Padrão"
        file: "blog-standard.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "blog-single"
        label: "Blog Único"
        file: "blog-single.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "blog-single-with-sidebar"
        label: "Blog Único com Sidebar"
        file: "blog-single-with-sidebar.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "blog-with-sidebar"
        label: "Blog com Sidebar"
        file: "blog-with-sidebar.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "blog-3-colum"
        label: "Blog 3 Colunas"
        file: "blog-3-colum.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "blog-2-colum"
        label: "Blog 2 Colunas"
        file: "blog-2-colum.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "project"
        label: "Projeto"
        file: "project.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "project-details"
        label: "Detalhes do Projeto"
        file: "project-details.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "project-details-2"
        label: "Detalhes do Projeto 2"
        file: "project-details-2.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "index-light"
        label: "Página Inicial Light"
        file: "index-light.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "index-3"
        label: "Página Inicial 3"
        file: "index-3.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "index-4"
        label: "Página Inicial 4"
        file: "index-4.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "team-details"
        label: "Detalhes da Equipe"
        file: "team-details.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      - name: "services-details"
        label: "Detalhes dos Serviços"
        file: "services-details.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "content", widget: "markdown" }

      # Adicione mais arquivos HTML conforme necessário

  - name: "assets"
    label: "Imagens e Arquivos"
    folder: "assets/img"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Arquivo", name: "file", widget: "file" }

  - name: "config"
    label: "Configurações do Site"
    files:
      - name: "settings"
        label: "Configurações"
        file: "data/settings.yml"
        fields:
          - { label: "Título do Site", name: "site_title", widget: "string" }
          - { label: "Descrição do Site", name: "site_description", widget: "text" }
          - { label: "E-mail de Contato", name: "contact_email", widget: "string" }
          - { label: "Links Sociais", name: "social_links", widget: "object", fields: [
              { label: "Twitter", name: "twitter", widget: "string" },
              { label: "Facebook", name: "facebook", widget: "string" },
              { label: "Instagram", name: "instagram", widget: "string" }
            ]}
