backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - name: "index"
        label: "Página Inicial"
        file: "index.html"
        fields:
          - { label: "Título", name: "title", widget: "string", default: "Guilimma | Creative Design" }
          - { label: "Home Navigation", name: "navHome", widget: "string", default: "Home" }
          - { label: "Digital Agency Navigation", name: "navDigitalAgency", widget: "string", default: "Digital Agency" }
          - { label: "Portfolio Interactive Navigation", name: "navPortfolioInteractive", widget: "string", default: "Portfolio Interactive" }
          - { label: "Creative Agency Navigation", name: "navCreativeAgency", widget: "string", default: "Creative Agency" }
          - { label: "Home Light Version Navigation", name: "navHomeLightVersion", widget: "string", default: "Home Light Version" }
          - { label: "Digital Agency Light Navigation", name: "navDigitalAgencyLight", widget: "string", default: "Digital Agency" }
          - { label: "Creative Agency Light Navigation", name: "navCreativeAgencyLight", widget: "string", default: "Creative Agency" }
          - { label: "Pages Navigation", name: "navPages", widget: "string", default: "Pages" }
          - { label: "About Us Navigation", name: "navAboutUs", widget: "string", default: "About Us" }
          - { label: "Team Members Navigation", name: "navTeamMembers", widget: "string", default: "Team Members" }
          - { label: "Team Details Navigation", name: "navTeamDetails", widget: "string", default: "Team Details" }
          - { label: "Projects Navigation", name: "navProjects", widget: "string", default: "Projects" }
          - { label: "Project Showcase Navigation", name: "navProjectShowcase", widget: "string", default: "Project Showcase" }
          - { label: "Project Details Navigation", name: "navProjectDetails", widget: "string", default: "Project Details" }
          - { label: "Contato Us Navigation", name: "navContatoUs", widget: "string", default: "Contato Us" }
          - { label: "Error Page Navigation", name: "navErrorPage", widget: "string", default: "Error Page" }
          - { label: "Serviços Navigation", name: "navServiços", widget: "string", default: "Serviços" }
          - { label: "Service Version One Navigation", name: "navServiceVersionOne", widget: "string", default: "Service Version One" }
          - { label: "Service Version Two Navigation", name: "navServiceVersionTwo", widget: "string", default: "Service Version Two" }
          - { label: "UX Strategy Navigation", name: "navUXStrategy", widget: "string", default: "UX Strategy" }
          - { label: "Branding Navigation", name: "navBranding", widget: "string", default: "Branding: Marcas com Identidade" }
          - { label: "UX Design Navigation", name: "navUXDesign", widget: "string", default: "UX Design: Experiências que Encantam" }
          - { label: "Social Media UX Navigation", name: "navSocialMediaUX", widget: "string", default: "Social Media UX" }
          - { label: "Keyword Research Navigation", name: "navKeywordResearch", widget: "string", default: "Keyword Research" }
          - { label: "Blog Navigation", name: "navBlog", widget: "string", default: "Blog" }
          - { label: "Blog Standard Navigation", name: "navBlogStandard", widget: "string", default: "Blog Standard" }
          - { label: "Blog With Sidebar Navigation", name: "navBlogWithSidebar", widget: "string", default: "Blog With Sidebar" }
          - { label: "Blog Grid Two Column Navigation", name: "navBlogGridTwoColumn", widget: "string", default: "Blog Grid Two Column" }
          - { label: "Blog Grid Three Column Navigation", name: "navBlogGridThreeColumn", widget: "string", default: "Blog Grid Three Column" }
          - { label: "Blog Single Navigation", name: "navBlogSingle", widget: "string", default: "Blog Single" }
          - { label: "Blog Single With Sidebar Navigation", name: "navBlogSingleWithSidebar", widget: "string", default: "Blog Single With Sidebar" }
          - { label: "Contato Navigation", name: "navContato", widget: "string", default: "Contato" }
          - { label: "Contato Question", name: "ContatoQuestion", widget: "string", default: "Have any Questions?" }
          - { label: "Contato Email", name: "ContatoEmail", widget: "string", default: "info@atozen.com" }

      - name: "about-us"
        label: "Sobre Nós"
        file: "about-us.html"
        fields:
          - { label: "Título", name: "title", widget: "string", default: "Sobre Nós" }
          - { label: "Conteúdo", name: "content", widget: "markdown", default: "Conteúdo sobre nós" }

      - name: "contact-us"
        label: "Contato"
        file: "contact-us.html"
        fields:
          - { label: "Título", name: "title", widget: "string", default: "Contato" }
          - { label: "Conteúdo", name: "content", widget: "markdown", default: "Conteúdo de contato" }

      - name: "404"
        label: "Página 404"
        file: "404.html"
        fields:
          - { label: "Título", name: "title", widget: "string", default: "Guilimma | Creative Design" }
          - { label: "Home Navigation", name: "navHome", widget: "string", default: "Home" }
          - { label: "Digital Agency Navigation", name: "navDigitalAgency", widget: "string", default: "Digital Agency" }
          - { label: "Portfolio Interactive Navigation", name: "navPortfolioInteractive", widget: "string", default: "Portfolio Interactive" }
          - { label: "Creative Agency Navigation", name: "navCreativeAgency", widget: "string", default: "Creative Agency" }
          - { label: "Home Light Version Navigation", name: "navHomeLightVersion", widget: "string", default: "Home Light Version" }
          - { label: "Digital Agency Light Navigation", name: "navDigitalAgencyLight", widget: "string", default: "Digital Agency" }
          - { label: "Creative Agency Light Navigation", name: "navCreativeAgencyLight", widget: "string", default: "Creative Agency" }
          - { label: "Pages Navigation", name: "navPages", widget: "string", default: "Pages" }
          - { label: "About Us Navigation", name: "navAboutUs", widget: "string", default: "About Us" }
          - { label: "Team Members Navigation", name: "navTeamMembers", widget: "string", default: "Team Members" }
          - { label: "Team Details Navigation", name: "navTeamDetails", widget: "string", default: "Team Details" }
          - { label: "Projects Navigation", name: "navProjects", widget: "string", default: "Projects" }
          - { label: "Project Showcase Navigation", name: "navProjectShowcase", widget: "string", default: "Project Showcase" }
          - { label: "Project Details Navigation", name: "navProjectDetails", widget: "string", default: "Project Details" }
          - { label: "Contato Us Navigation", name: "navContatoUs", widget: "string", default: "Contato Us" }
          - { label: "Error Page Navigation", name: "navErrorPage", widget: "string", default: "Error Page" }
          - { label: "Serviços Navigation", name: "navServiços", widget: "string", default: "Serviços" }
          - { label: "Service Version One Navigation", name: "navServiceVersionOne", widget: "string", default: "Service Version One" }
          - { label: "Service Version Two Navigation", name: "navServiceVersionTwo", widget: "string", default: "Service Version Two" }
          - { label: "UX Strategy Navigation", name: "navUXStrategy", widget: "string", default: "UX Strategy" }
          - { label: "Branding Navigation", name: "navBranding", widget: "string", default: "Branding: Marcas com Identidade" }
          - { label: "UX Design Navigation", name: "navUXDesign", widget: "string", default: "UX Design: Experiências que Encantam" }
          - { label: "Social Media UX Navigation", name: "navSocialMediaUX", widget: "string", default: "Social Media UX" }
          - { label: "Keyword Research Navigation", name: "navKeywordResearch", widget: "string", default: "Keyword Research" }
          - { label: "Blog Navigation", name: "navBlog", widget: "string", default: "Blog" }
          - { label: "Blog Standard Navigation", name: "navBlogStandard", widget: "string", default: "Blog Standard" }
          - { label: "Blog With Sidebar Navigation", name: "navBlogWithSidebar", widget: "string", default: "Blog With Sidebar" }
          - { label: "Blog Grid Two Column Navigation", name: "navBlogGridTwoColumn", widget: "string", default: "Blog Grid Two Column" }
          - { label: "Blog Grid Three Column Navigation", name: "navBlogGridThreeColumn", widget: "string", default: "Blog Grid Three Column" }
          - { label: "Blog Single Navigation", name: "navBlogSingle", widget: "string", default: "Blog Single" }
          - { label: "Blog Single With Sidebar Navigation", name: "navBlogSingleWithSidebar", widget: "string", default: "Blog Single With Sidebar" }
          - { label: "Contato Navigation", name: "navContato", widget: "string", default: "Contato" }
          - { label: "Contato Question", name: "ContatoQuestion", widget: "string", default: "Have any Questions?" }
          - { label: "Contato Email", name: "ContatoEmail", widget: "string", default: "info@atozen.com" }

      - name: "services"
        label: "Serviços"
        file: "services.html"
        fields:
          - { label: "Título", name: "title", widget: "string", default: "Serviços" }
          - { label: "Conteúdo", name: "content", widget: "markdown", default: "Conteúdo dos serviços" }

      - name: "portfolio"
        label: "Portfólio"
        file: "portfolio.html"
        fields:
          - { label: "Título", name: "title", widget: "string", default: "Portfólio" }
          - { label: "Conteúdo", name: "content", widget: "markdown", default: "Conteúdo do portfólio" }

      - name: "team"
        label: "Equipe"
        file: "team.html"
        fields:
          - { label: "Título", name: "title", widget: "string", default: "Equipe" }
          - { label: "Conteúdo", name: "content", widget: "markdown", default: "Conteúdo da equipe" }

  - name: "assets"
    label: "Imagens e Arquivos"
    folder: "assets/img"
    create: true
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Arquivo", name: "file", widget: "file" }

  - name: "config"
    label: "Configurações do Site"
    files:
      - name: "settings"
        label: "Configurações"
        file: "data/settings.yml"
        fields:
          - { label: "Título do Site", name: "site_title", widget: "string" }
          - { label: "Descrição do Site", name: "site_description", widget: "text" }
          - { label: "E-mail de Contato", name: "contact_email", widget: "string" }
          - { label: "Links Sociais", name: "social_links", widget: "object", fields: [
              { label: "Twitter", name: "twitter", widget: "string" },
              { label: "Facebook", name: "facebook", widget: "string" },
              { label: "Instagram", name: "instagram", widget: "string" }
            ]}

      - name: "Teste"
        label: "Teste Netlify"
        file: "testenetlify.html"
        fields:
          - label: "Título da Página"
            name: "pageTitle"
            widget: "string"
            default: "My Website"
          - label: "Título do Cabeçalho"
            name: "headerTitle"
            widget: "string"
            default: "Welcome to My Website"
          - label: "Descrição do Cabeçalho"
            name: "headerDescription"
            widget: "text"
            default: "This is a simple example of a static site."